package FPL.SIDSD.Entities;
// Generated 20 oct. 2022 à 19:40:51 by Hibernate Tools 4.3.5.Final
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Etudiant generated by hbm2java
 */
@Entity
@Table(name = "etudiant", catalog = "espace_etudiant_fpl_2023")
public class Etudiant implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Filiere filiere;
	private String nom;
	private String prenom;
	private String cne;

	public Etudiant() {
	}

	public Etudiant(int id, String nom, String prenom, String cne, Filiere filiere) {
		this.id = id;
		this.filiere = filiere;
		this.nom = nom;
		this.prenom = prenom;
		this.cne = cne;
	}
 	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFiliere", nullable = false )
	public Filiere getFiliere() {
		return this.filiere;
	}
	public void setFiliere(Filiere filiere) {
		this.filiere = filiere;
	}

	@Column(name = "nom", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "cne", nullable = false)
	public String getCne() {
		return this.cne;
	}

	public void setCne(String cne) {
		this.cne = cne;
	}
}
